{% set name = "copykitten" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/copykitten-{{ version }}.tar.gz
  sha256: bda13d614ffb38147d4fce5217d4f2397967514f5ea09fb8d5c5cf5d16028e58

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.3,<2.0
    - pip
  run:
    - python

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Klavionik/copykitten
  summary: A robust, dependency-free way to use the system clipboard in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
