{% set name = "copykitten" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copykitten-{{ version }}.tar.gz
  sha256: 924e5c091cf93ab636d56a6e7a138429c91ebc60dcabbf4d165cd8ddb891703a

build:
  skip: true  # [py<38 or py>312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=1.3,<2.0
    - pip
  run:
    - python

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Klavionik/copykitten
  summary: A robust, dependency-free way to use the system clipboard in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
